sudo: required
services:
  - docker
language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
env:
  matrix:
    - CXX=g++-4.8
  global:
    - secure: "nDBELEuMuv9wHXOLUg1sJmIt8krzB8siNrJ/oouDa5n2m1l0l5ekWSN3YzsAkok+H9DNdcXYH+vuorUhau++iYjMqKRJKNYHYbKbduoVEkX8WExmYTCu0c8DjrijHLY4XOAaJ2ZCL2xSjPJiRWsyPjYKrD+jcule7AyOvxSDyUm16FTxSr4OSCfJIxkWjnLas/jdZeNUBf/CU4YXFeH0entI+ebkH40HtFNFywvOdm73Yff4ptGH81PyBV6ROGhahCFmwklt0qn03Xivob0y+ZZFqRJfuIShdXfy/vFRVHORx760nvpHjUGR/bZqAweMhA86JEL5GJ/iUllzedfbu1+y1XBZvmhqY6Q7Jg1XI635vsPfMa4tHQX77FMp9CN8Y9vpQ/IcgDH5W8Q9oqH9i65BcYvqKemh/1gn6wP1ADwxPeH1qOOn6NuFK32CaTMly5aMvWacVfmhQ4CxaDbJKbdPy7MK25xMTC76nbuTCMF8lsjT6clc07ExX4odjVnU6BfqXTvVDHaSki48LT+bebIu0Xi6aWB5x8eC+L+M3VpbvWldGDmgY8iW2uWow0JsyCHDLObTJzoaEfU0qdZxJT3vxygKecTdfdK7VGQGtInWUEKC+yO0099jsNT3sI85OfvEVoN3us4feP5XdPJc48SeTWPko4bdQy+gwuhy0bo=" # DOCKER_EMAIL
    - secure: "4NLvgSkFki33qifdkcO/CVKDk174zLNA3yxGDASBnyCaHmBSnOLM1zRg21ryZE5zz+tdLdRoQjrgUkNFqLeF/Zefd5bp2BuuHJ9VSyEccLhf3H/nVAPCBQxNothrQbMLp81ZWp5CmVPp7jhYJABJW+ApV88ljunNeLEyz5iQR77SqCFVtfrZlUPGzaugFJPiFs0a1I56ccsAEoUIYC3AdSKbIY5P9Mj0mEUHTTzg+Z5xifjbJjoEJy1cLuO9rKie6rGiXrJywgJZ1xW6qnt8PGSff7uThFElgKI0RYbycYL9ClDViuXZ2alaK0PdJpw1x0s7DGJxkPq83GFEDVh8q2hJYuyqAURm91kjW5jtzkB5pA1lir1YNW25JvMfLSyR/d5aw60WR6j9zErFHGkKmW3U7r4tbbcXBzulH/fULpXAEwUCGfkcqxGy2IygEUxQ1L79FW9o1zNccaR/9bkQkD1fWkLX2LSUCJZD+JyWg/xxXkTqYxpLa8yAcGch50tfcESoa7cN+ZkzByacIcadNBUwfgnuC0Fz93UOlEP3PUypRtDYNSCoakVK+b8eIgEQToaWxltHd54p5dBaWfWakoD+gXqAbihRdlbVDjz7oORj2aNw1hdrUvbiR9akm7EVb0Lyxm51paGBnbXeXWqN50nP+OxnxEcG0hYhx3gn8N4=" # DOCKER_USER
    - secure: "q+tByVY+0ERbnFzj4XloajRiamI3Dl0EL3On7f8VuAht5AXNmheZtSrdUUSBbraJAsaohSTL5grBMpss5Iko+5QRXdaOGsNtlxOb7dYWWoW9gpNl1/ru+Ys1/Eu52X0nmSiMvCOyX1/3MDx/6iPaOSavTb58jT6OQJH2QNetiVslACuJ/C0cLrA7u8pM8PbwO3CcvETEBCCai2HeLL/1llH49CaRXI7guG0dQ2qeqCgrJ1ikpe71yhIsbQQ0XvfOn/RjmQOYZp6U5o8uWj9vA7Xa2dWGTKpSV31TShNE2elfddGcWTENfhmaQQivIydyI8Ey07ypTsWKHqBZAxA6WXsrQh5CYwiw2e6N9/EO28Y+AOwlN+nNtzwJmbwB6AQE6g/UdoB9MEWrICXNHd/7O43d42zgX4zBbXc3e6ZhlpyTqGw49b6KeLPJqOm+h1gNQfNcSj9dAYn6BFP9KFp+sY8CFCtuRJrGBe+HSonP/jhn/LtH9/O+qE7QZAVqU2C+u0hjGsssYFF+dUcx97dQ+4NUZjeb2yEjzR4EIUwcNANhlqeoteA/kSgH/E/9he8hQkYESBL9bxHvgNkeb5QbnLhLrgTpEZAZ7iwvroXGnRGFU4GE9Fy5bUTzpa/lfl4xU3CW69JXx5LtnIrx3uS3y3PGElOI+uCEdOPnE+MpL3k=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - npm run coveralls
  - npm run coverage-clean
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export DOCKER_REPO=cheton/cnc
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TRAVIS_TAG; fi
  - docker push $DOCKER_REPO
