sudo: required
dist: trusty

services:
  - docker

language: node_js

os:
  - linux
  - osx

node_js:
  - '4'
  - '5'

env:
  global:
    - secure: "KPf6trtYLBDc2S/fF7H4VkNOAQ2Gc9sFj3v8aHOhNWDagACEHaPjIZdr3MGmzXji2EyQqtm6SxBxzdMbe1BNY5GRALgGI2fSyra+VwjhUeOB/UJ8oZuxhqnywbF77lbZgUYK/kOWHgCKGQxRsVZyytgK2CihOwPwzSp/CWUhBjlyjtDpUOMJXfc0USg05imR9LcwdW9o84uXGyI3XwHhqsA5szlu09Oxz+O//TMCHobb8o9b13N8Oxhdu9mgzynXCEo7TG4rwbmx2t7ymfM0TfEqfEsOOQ/A7iPJ4lxQ+FKGoKaqfITuZtUmzd4RaCK8zRVg/dYbXX2qF/RWRBKwIAfBLNLYYdFxleaBaNgGGyQw8TpNkm80u5ilmIDCrw79m0MqePZXcL4pdfRC9PBE2PO55tX/Podhk9HKovixvB4qxUj3Y45ORtSE2TO78W3Cs54JTQVNh4xz8Tzp67DWwNXN5XnwkVyvRugaCHV1gUuJWuJTUr6Bdoad9vid+GUKqNoBlTTgkjfc0/TDSuDFnAbnhdga4xFoFLnpTDpCaZrr1NWfhVCepGqY7I4qLcie/Bobpr6n8UuBRg6devdcBZJxAYKyC4SkfqfkJe36TmTViz7GCs698CAPteJ2ypifeERT9zYu0JYeofEi49bPxevaaFICxzUE2WIAlGeGIw0=" # DOCKER_EMAIL
    - secure: "Xh5xnUckiGwr3pcl44c8A91p2AyhJXMpGzDPpTk+63ZeM0nDnUh1/1StqW+5Bfx24MI6HtkOiGa7zTn8HbDMWXVN7s+eZ0eC28GI63EsKyivsMyylR+mwMKsAHcxbfZvFaDJiYE/s1FXXVdIr3PpNVxlncbuZiTQ+i+sr4iD+B14UV+GTwgbpyNEF2jSK+MlV0XAn6AK4kc6fd3Zx2guG9Kv8slwFcK7Kwjpa4C+t0ZX85wiqlPBhC42nhx6eRUwWbf/4rySd/4RhHXan+zsBWBjUHLhjzMvwsahqPg0yBzkFoZ3ozUQqv9NhmyjEANCAAj1vcOoFZ0nikgfR1WqeMEcKfTFbV0QVfqnEyYHN2ZUmvOzv2gih26gHaY7E2Dte6u96CSv5TgwYtiCBZzc0vHO8p2+heLfourhqdQhanElq4nthBffKJled5dOcq6UAINK85ZwzS+7EZG79idGETR7vvCiaLLuhCn4kFdo1fLOCTQ+FJAOYw3uSk6n1YlNbxNJ7RwykgRB/9MgbJHc9o67C/Y3NEzBRErSctqfZ9Rg6gICM8dkwoBh0652FDn4E/TCkpfKbpTkRkJoFzRxe9joFTYvkt+fIYwokyajgt/qlpb6XQiFiUqdlWcWcYDNbBSnIMfH4L61ktMtCCcv85Iw98d1bxi93r/UdyhWOuQ=" # DOCKER_USER
    - secure: "vthH2fNi44W4+21OxLnmeb41y9T+v5p4vpWgj5DG/LuVfJNw5fNvnitXdwe3UR0EQCvH0ow4mn4I2avqvn5G6PSDmgpzTHcw8OJt/cGhXXsN629tdccG+rHG8xFneRACnSJOmZ3rU038igAlZt7PdraM68ZVdwZfXEDua06qb4FODBWNZtiUJ89AyYib5DoYjde18sEHqNZEp1ruhcfZArzexnxJ7G63Qe3SmxBS5Z7jC18sGyTI3FbUyKUlqYsxG8rcqTy5QOKa6Y0P1TPPHmr517uO4YfxhQX6Lcrn+DgvHH/n6pzlBeGgXm5XZB+MN6iRM8NRo1VmQ8Ecm3sFb6UZvESB0wx3EI5DPde/rxE6fwhTP/d+95qSrZUvuqLOGfa6Zb5JsgKzK4St2EVb6hs5qqTnIifGZQZ4NJrhTe737kE4FsJbK8dQmNMwMlNVbCmnYeZmWh3aJgXp4fjk/RyomFvfGLjNchVIM6iZw2DlqLJm2Wl4Dsb1blj4tfuL0+UlA9YiF2V6ycn5sWdq5JiGsWhkyARnCiSFc5lu6TbvKt8k5CQIwZXshoKyv8IIQkEubGVQRI9D8nDrgrbOt8+lIEU6Ibfbi1CzuPpv95GodWLCEyf6KXf8EHr+tEbKPwpbNzIsPWEqMuPQ6F3AWtGnuuAvfLm/5+/OXNKxT3o=" # DOCKER_PASS
    - secure: "4UQ481SPBJlRZcXtpFUl4Y4MagUfLD/UL3TkYi5s1eNlo3SUHk/gsFBPtwfUtlkvic40GrRkdwYAhr3UnmvnkVO9LQU4UsXEKlk/006JOLJXzkI0BQqSk6yzIG+2QIPgcZfeNSOsHFbWqh7LWNH8TPELnBfBh4V+9Yi+y7sC3lDtkI/VUu1QIFVJbt7509TF3cVgqN6m6uuZR4TRCEBXeZ4WqBdxM52qjQJbAJullkoTIaSYM565e1Ha/3Xb7gP04R+FdbcjxnZiE+KWTnYBUf1eTRmdJ/lvqY2fKvIC1zuzg8mQI1GUrcb+phWgrkacxQp7T4lb2iEu1JEnYoOfv/V7ChpvsbDZrtRRx3V+VLBn/gdliFgCdHbNGDlUH6ZkI4KxbGE6AEChQTMrYXJd/SjlGKvmA/jQkweyIkcIjJfQotcwWGWnPWl889RZtjIe90bqW/hao3Nl11oRDvlkYS25oXAxp1I8aC66nEryM5NXqY8FZ1MyMcujK+aF70IUoNG91dCaksIWyJbC3V+P7O5N5R7RE+8ya21XVYf+3rFjzTnKbgTXH4KE8k6mo+bOsc1o+gN0X9EoqBeO4iKM+WXc334o3WRn+F4J9FMBbO4eNvVBA/BLhl2nBsoOii1OpoHRIZkr5JAX91ws9s/hxCvGYHm7txIVG7dfljYdK20=" # GITHUB_TOKEN
    - GOPATH=$HOME/gopath
    - PATH=$HOME/gopath/bin:$PATH

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - gcc-multilib
      - g++-multilib

before_install:
  - git --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - go version
  - go env
  # https://github.com/aktau/github-release
  - go get github.com/aktau/github-release
  - github-release --version
  #
  # https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x
  #
  # Use brew to install required packages.
  #
  # To build app in distributable format for Windows on OS X:
  # $ brew install Caskroom/cask/xquartz wine mono
  #
  # To build app in distributable format for Linux on OS X:
  # $ brew install ruby gnu-tar libicns graphicsmagick
  #
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - gem install fpm
  # npm v3
  - npm install -g npm

script:
  - npm run build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run electron-builder:darwin-x64; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run electron-builder:linux-x64; fi

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" != "5" ]]; then exit 0; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -c 'cd output; zip -q -r cncjs-darwin-x64.zip cncjs-darwin-x64/'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -c 'scripts/travis-release-darwin-x64.sh output/cncjs-darwin-x64.zip'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'cd output; zip -q -r cncjs-linux-x64.zip cncjs-linux-x64/'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'scripts/travis-release-linux-x64.sh output/cncjs-linux-x64.zip'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'scripts/travis-docker-build.sh'; fi
